### ISSUE TITLE
Порождающий паттерн

### ISSUE THREAD

**Issue by timDVN** [AntonGlinisty/Pac#3]
Какой порождающий паттерн вы используете? Объясните свой выбор

**Comment by AntonGlinisty** [comment]
Привет, я использовал фабрику. На данный момент проект в статусе разработки, сделал промежуточный пуш.

**Comment by AntonGlinisty** [comment]
Использовал фабрику, т.к. в моей игре присутствуют спрайты(призраки), обладающие похожим поведением и свойствами. Благодаря фабричному методу, у меня существует интерфейс для создания отдельных объектов подклассов. То есть мне не нужно запоминать или хранить все необходимые параметры отдельных спрайтов, я создаю объект по имени призрака. Фабричный метод позволил централизовать создание объектов и все стало намного удобнее.
